"""
SQL Tool for Database Query Execution

This module implements the SQL tool that the agent uses to execute database queries.
The tool translates natural language requests into SQL queries, executes them against
the PostgreSQL database, and returns structured JSON results. Also injects results
into Streamlit's session state for frontend display.
"""

# ================== Imports ==================
import json
import pandas as pd
from llama_index.core.tools import FunctionTool

# Try to import streamlit for session state injection (optional dependency)
try:
    import streamlit as st
    STREAMLIT_AVAILABLE = True
except ImportError:
    STREAMLIT_AVAILABLE = False

from config.database import run_sql_query
from tools.shared_state import set_last_query_result


# ================== Tool Function ==================

def sql_tool_function(query: str) -> str:
    """
    Execute a SQL query on the robot_vacuum_orders table and return results.
    
    Takes a SQL query string generated by the LLM, executes it against the PostgreSQL
    database, and returns results in JSON format. Stores the DataFrame in shared state
    and Streamlit session state for access by other tools and the frontend.
    
    The database table contains comprehensive order data including:
    - **Order information**: OrderID, OrderDate, CustomerID, CustomerName
    - **Financial data**: ShippingCost (NUMERIC), TotalAmount (NUMERIC), ProductPrice (NUMERIC)
    - **Product data**: Quantity (INTEGER), ProductName, ManufacturerName
    - **Shipping data**: ShippingCarrier, Region, DeliveryStatus
    - **Review data**: ReviewRating (NUMERIC), ReviewDate (TIMESTAMP)
    
    Args:
        query: SQL query string in PostgreSQL syntax. Must be a valid SELECT statement
            that can be executed against the robot_vacuum_orders table.
    
    Returns:
        str: JSON string representation of the query results with structure:
        - **rows**: List of dictionaries, each representing one row
        - **row_count**: Total number of rows returned
        - **columns**: List of column names
        - **message**: Success message indicating data is available for visualization
    
    Note:
        If the query fails, returns an error message string instead of JSON.
    """
    try:
        df = run_sql_query(query)
        
        # Store the dataframe for the visualization tool to access
        set_last_query_result(df)
        
        # Inject into Streamlit session state if available
        # This allows the frontend to display the data directly without parsing
        if STREAMLIT_AVAILABLE:
            try:
                st.session_state['temp_sql_df'] = df
                st.session_state['temp_sql_query'] = query
            except Exception:
                # Streamlit not in proper context, continue without injection
                pass
        
        # Convert DataFrame to JSON for agent consumption
        # Using 'records' format creates a list of dictionaries, which is easier
        # for the LLM to understand and process
        result_json = df.to_json(orient='records', date_format='iso')
        
        # Build structured result with metadata
        result = {
            "rows": json.loads(result_json),
            "row_count": len(df),
            "columns": list(df.columns),
            "message": f"Query executed successfully. Retrieved {len(df)} rows. Data is now available for visualization."
        }
        
        return json.dumps(result, indent=2)
    except Exception as e:
        return f"Error executing SQL query: {str(e)}"


# ================== Tool Creation ==================

def create_sql_tool() -> FunctionTool:
    """
    Create a FunctionTool wrapper for the SQL tool function.
    
    This function wraps sql_tool_function in a LlamaIndex FunctionTool so the agent
    can discover and use it. The description is carefully crafted to help the LLM
    understand when and how to use this tool effectively.
    
    Returns:
        FunctionTool: Configured tool instance that the agent can call with:
        - **name**: "sql_tool"
        - **description**: Explains the tool's purpose and the database schema
        - **function**: sql_tool_function
    """
    return FunctionTool.from_defaults(
        fn=sql_tool_function,
        name="sql_tool",
        description=(
            "Useful for translating a natural language query into a SQL query "
            "for the table 'robot_vacuum_orders'. Returns the data as JSON. "
            "Use this tool to fetch data from the database. "
            "The table contains order data with columns like ShippingCost (NUMERIC), "
            "TotalAmount (NUMERIC), Quantity (INTEGER), ShippingCarrier, Region, etc."
        )
    )

