"""
Visualization Tool for Plotly Chart Generation

This module implements the visualization tool that the agent uses to create Plotly charts.
The tool executes Python code generated by the LLM to create interactive visualizations.
Pre-injects plotly modules and cleans the code to prevent import conflicts and ensure
the figure is properly captured and returned.
"""

# ================== Imports ==================
import io
import json
import re
import contextlib
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from llama_index.core.tools import FunctionTool

# Try to import streamlit for session state injection (optional dependency)
try:
    import streamlit as st
    STREAMLIT_AVAILABLE = True
except ImportError:
    STREAMLIT_AVAILABLE = False

from tools.shared_state import get_last_query_result


# ================== Tool Function ==================

def python_visualizer_tool_function(code: str) -> str:
    """
    Execute Python code to create Plotly visualizations.
    
    Takes Python code generated by the LLM and executes it in a safe environment to
    create Plotly figures. Pre-injects plotly modules and pandas to prevent import
    conflicts, and cleans the code to remove fig.show() calls and conflicting imports.
    The resulting figure is converted to JSON and injected into Streamlit session state.
    
    The code should assume data is already available in a DataFrame named `df`.
    The code should create a Plotly figure and assign it to a variable named `fig`.
    
    Example code that would work:
        fig = px.bar(df, x='ShippingCarrier', y='TotalAmount', title='Revenue by Carrier')
    
    Args:
        code: Python code string that creates a Plotly figure. The code should:
            - Use the pre-injected `df` DataFrame (no need to define it)
            - Use `px` (plotly.express) or `go` (plotly.graph_objects)
            - Assign the figure to a variable named `fig`
            - NOT call `fig.show()` (this is automatically removed)
    
    Returns:
        str: JSON string representation of the result with structure:
        - **success**: True if figure was created successfully
        - **figure_json**: Plotly figure as a JSON-serializable dictionary
        - **stdout**: Any output printed during code execution
        - **stderr**: Any errors printed during code execution
        - **message**: Success message
    
    Note:
        If execution fails or no figure is created, returns an error message in JSON format.
    """
    try:
        # Priority 1: Try to get dataframe from Streamlit session state
        # This is the most reliable method when running in Streamlit context
        df = None
        if STREAMLIT_AVAILABLE:
            try:
                if 'session_state' in st.__dict__ and 'temp_sql_df' in st.session_state:
                    df = st.session_state['temp_sql_df']
            except Exception:
                pass
        
        # Priority 2: Fallback to global variable (for standalone execution)
        # This allows the tool to work even when Streamlit is not available
        if df is None or df.empty:
            df = get_last_query_result()
        
        if df is None or df.empty:
            return json.dumps({
                "error": "No data available. Please run a SQL query first using sql_tool to fetch data.",
                "hint": "The visualization tool requires data from a previous SQL query."
            })
        
        # Create execution environment with pre-injected modules
        # I pre-inject these to prevent import conflicts when the agent generates code
        # that tries to import plotly or pandas again
        local_vars = {
            'pd': pd,
            'pandas': pd,
            'go': go,
            'graph_objects': go,
            'px': px,
            'plotly': {'express': px, 'graph_objects': go},
            'plotly.express': px,
            'plotly.graph_objects': go,
            'df': df,
        }
        
        # Capture stdout and stderr to include in the response
        # This helps debug issues if the generated code has problems
        stdout_capture = io.StringIO()
        stderr_capture = io.StringIO()
        
        # Clean the code before execution
        # Remove fig.show() calls to prevent pop-ups, and remove conflicting imports
        code_cleaned = code
        if 'fig.show()' in code:
            code_cleaned = re.sub(r'fig\.show\(\)', '# fig.show() removed - figure will be displayed in UI', code_cleaned)
        
        # Remove import statements that would conflict with pre-injected modules
        # Comments them out rather than deleting to preserve line numbers for error messages
        code_cleaned = re.sub(r'^import\s+plotly\.express\s+as\s+px\s*$', '# plotly.express already imported as px', code_cleaned, flags=re.MULTILINE)
        code_cleaned = re.sub(r'^import\s+plotly\.graph_objects\s+as\s+go\s*$', '# plotly.graph_objects already imported as go', code_cleaned, flags=re.MULTILINE)
        code_cleaned = re.sub(r'^import\s+plotly\.express\s*$', '# plotly.express already imported as px', code_cleaned, flags=re.MULTILINE)
        code_cleaned = re.sub(r'^import\s+plotly\.graph_objects\s*$', '# plotly.graph_objects already imported as go', code_cleaned, flags=re.MULTILINE)
        
        # Execute the cleaned code in a safe environment
        exec_error = None
        try:
            with contextlib.redirect_stdout(stdout_capture), contextlib.redirect_stderr(stderr_capture):
                exec(code_cleaned, {"__builtins__": __builtins__}, local_vars)
        except Exception as e:
            exec_error = str(e)
            stderr_capture.write(str(exec_error))
        
        # Extract the figure from the execution environment
        # Uses .get() to safely handle cases where 'fig' might not exist
        fig = local_vars.get('fig')
        
        if fig is None:
            error_msg = {
                "error": "No Plotly figure named 'fig' was created by the code",
                "code_executed": code_cleaned,
                "stdout": stdout_capture.getvalue(),
                "stderr": stderr_capture.getvalue() if not exec_error else stderr_capture.getvalue() + f"\nExecution error: {exec_error}",
                "hint": "Make sure your code creates a variable named 'fig', e.g., 'fig = px.pie(df, ...)'"
            }
            return json.dumps(error_msg, indent=2)
        
        # Verify that fig is actually a Plotly figure object
        # This prevents errors if the code accidentally creates a variable named 'fig' that isn't a figure
        if not hasattr(fig, 'to_json'):
            error_msg = {
                "error": f"Variable 'fig' exists but is not a Plotly figure (type: {type(fig).__name__})",
                "fig_type": str(type(fig)),
                "stdout": stdout_capture.getvalue(),
                "stderr": stderr_capture.getvalue()
            }
            return json.dumps(error_msg, indent=2)
        
        # Convert Plotly figure to JSON
        # This serializes the figure so it can be passed through the agent's response
        try:
            fig_json = fig.to_json()
            fig_dict = json.loads(fig_json)
        except Exception as e:
            error_msg = {
                "error": f"Failed to convert Plotly figure to JSON: {str(e)}",
                "stdout": stdout_capture.getvalue(),
                "stderr": stderr_capture.getvalue()
            }
            return json.dumps(error_msg, indent=2)
        
        # Inject into Streamlit session state if available
        # This allows the frontend to display the figure directly without parsing
        if STREAMLIT_AVAILABLE:
            try:
                st.session_state['temp_plot_json'] = fig_dict
                st.session_state['temp_code'] = code
            except Exception:
                pass
        
        # Return structured result with figure JSON
        result = {
            "success": True,
            "figure_json": fig_dict,
            "stdout": stdout_capture.getvalue(),
            "stderr": stderr_capture.getvalue(),
            "message": "Plotly figure created successfully"
        }
        
        return json.dumps(result, indent=2)
        
    except Exception as e:
        return json.dumps({
            "error": f"Error executing visualization code: {str(e)}",
            "stdout": stdout_capture.getvalue() if 'stdout_capture' in locals() else "",
            "stderr": stderr_capture.getvalue() if 'stderr_capture' in locals() else ""
        })


# ================== Tool Creation ==================

def create_visualizer_tool() -> FunctionTool:
    """
    Create a FunctionTool wrapper for the visualization tool function.
    
    This function wraps python_visualizer_tool_function in a LlamaIndex FunctionTool so
    the agent can discover and use it. The description emphasizes that the dataframe
    is already available and explains the expected code structure.
    
    Returns:
        FunctionTool: Configured tool instance that the agent can call with:
        - **name**: "python_visualizer_tool"
        - **description**: Explains the tool's purpose, that df is pre-available, and
            that chart types should be chosen dynamically
        - **function**: python_visualizer_tool_function
    """
    return FunctionTool.from_defaults(
        fn=python_visualizer_tool_function,
        name="python_visualizer_tool",
        description=(
            "Useful for generating Plotly charts. "
            "The dataframe from the previous SQL query is ALREADY available "
            "in the environment as the variable `df`. You do NOT need to pass the data. "
            "Just write Python code that uses `df`. "
            "The code should create a Plotly figure and assign it to a variable named 'fig'. "
            "You can use plotly.express (px) or plotly.graph_objects (go). "
            "Examples: px.bar(df, x='col1', y='col2'), px.pie(df, values='col1', names='col2'), "
            "px.line(df, x='col1', y='col2'). "
            "DO NOT use fig.show() in your code. Just assign the figure to 'fig' variable. "
            "Choose the chart type (bar, line, pie, scatter, etc.) dynamically "
            "based on the data characteristics and user request. Do NOT use hard-coded rules."
        )
    )

